env:
  browser: true
  commonjs: true
  es6: true
  node: true
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      ignoredNodes:
        - JSXElement *
  semi:
    - error
    - always
  max-len:
    - error
    - code: 180
  keyword-spacing:
    - error
    - after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - asyncArrow: always
      anonymous: never
      named: never
  no-unused-vars:
    - error
    - argsIgnorePattern: "re[q|s]"
  brace-style: error
  node/shebang: 0
  quotes:
    - error
    - single
  quote-props:
    - error
    - as-needed
  react/prop-types: 0
  react/jsx-indent-props: 0
  react/display-name: 0



